apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: httpd-ex
  name: httpd-ex
  namespace: test
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: httpd-ex:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      ref: master
      uri: https://github.com/openshift/httpd-ex.git
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: httpd:2.4
        namespace: openshift
    type: Source
  triggers:
  - imageChange:
    type: ImageChange
  - type: ConfigChange
